apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-deployment
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        resources: {}
status: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"wordpress-deployment"},"name":"wordpress-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordpress-deployment"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"wordpress-deployment"}},"spec":{"containers":[{"image":"wordpress:4.8-apache","name":"wordpress","resources":{}}]}}},"status":{}}
  creationTimestamp: "2025-01-11T14:37:08Z"
  generation: 1
  labels:
    app: wordpress-deployment
  name: wordpress-deployment
  namespace: default
  resourceVersion: "12726"
  uid: f1422d83-bf24-4731-a440-42f18f5167bd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_PASSWORD
          value: password
        image: wordpress:4.8-apache
        imagePullPolicy: IfNotPresent
        name: wordpress
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-01-11T14:37:08Z"
    lastUpdateTime: "2025-01-11T14:37:08Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-01-11T14:37:08Z"
    lastUpdateTime: "2025-01-11T14:37:08Z"
    message: ReplicaSet "wordpress-deployment-75c645c8ff" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
