apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-service
  name: wordpress-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-service
  type: LoadBalancer
status:
  loadBalancer: {}
