plugins=(git zsh-autosuggestions)

alias clear_history='echo "" > ~/.zsh_history & exec $SHELL -l'
alias brew_fix='eval $(~/.linuxbrew/bin/brew shellenv) && test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv) && test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv) && test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile && source $ZSH/oh-my-zsh.sh'
alias vmshared='/usr/bin/vmhgfs-fuse --enabled && sudo vmhgfs-fuse .host:/ /mnt/hgfs -o allow_other'
alias editzsh='echo "editzsh => vim ~/.zshrc" && vim ~/.zshrc'
alias applyzsh='echo "applyedit => source ~/.zshrc" && source ~/.zshrc'
alias editapplyzsh='echo "editapplyzsh => editzsh && echo "" && applyedit" && editzsh && echo "" && applyedit'
alias authedit='echo "sudo vim ~/.ssh/authorized_keys" && mkdir -p ~/.ssh && vim ~/.ssh/authorized_keys'
alias catssh='echo "cat ~/.ssh/id_rsa.pub" && sudo cat ~/.ssh/id_rsa.pub'
alias genssh='echo "ssh-keygen -t rsa -b 4096 -C email'
alias sethost='echo "hostnamectl set-hostname xName"'
alias gethost='echo "gethost => hostnamectl hostname" && hostnamectl hostname'
alias rsnet='echo "rsnet => systemctl restart NetworkManager.service (https://bit.ly/3g80uAR)" && systemctl restart NetworkManager.service'
alias ngnsu='echo "ngnsu => sudo systemctl status nginx (https://bit.ly/2I8MRVo)" && sudo systemctl status nginx'
alias ngnsp='echo "ngnsp => sudo systemctl stop nginx" && sudo systemctl stop nginx'
alias ngnst='echo "ngnst => sudo systemctl start nginx" && sudo systemctl start nginx'
alias ngnrt='echo "ngnrt => sudo systemctl reload nginx" && sudo systemctl reload nginx'
alias ngnenb='echo "ngnenb => sudo systemctl enable nginx" && sudo systemctl enable nginx'
alias ngndis='echo "ngndis => sudo systemctl disable nginx" && sudo systemctl disable nginx'
alias vmedit='echo "vmedit => vim ~/.vimrc && to add line numer add set number (https://bit.ly/3mHpBNt)" && vim ~/.vimrc'
alias vimline='echo "vimline => echo https://stackoverflow.com/a/42619212" && rm -rf ~/.vimrc && echo "set number" >> ~/.vimrc && echo "syntax on" >> ~/.vimrc'

alias krun='echo "krun => kubectl apply -f ." && kubectl apply -f .'
alias k0='echo "k0 => kubectl scale deployment my-deployment --replicas=0" && kubectl scale deployment my-deployment --replicas=0'
alias kdel='echo "kdel => deleting all pods, service, pvc" && kubectl delete replicaset --all && kubectl delete pods --all && kubectl delete service --all && kubectl delete pvc --all && clear && kubectl get all'
alias kfw='echo "kubectl port-forward service/_name hostPort:dockerPort"'
alias kip='echo "minikube service --all --url" && minikube service --all --url'
alias epass='echo "echo -n _pass | base64"'
alias mip='echo "minikube service --all" && minikube service --all'
alias kget='echo "kubectl get all" && kubectl get all'
alias npzsh='notepad-plus-plus ~/.zshrc && applyzsh'
alias codezsh='code ~/.zshrc && applyzsh'
alias gezsh='code ~/.zshrc && applyzsh'
alias apt_update='echo "sudo apt update -y" && sudo apt update -y && sudo apt-get update -y && sudo apt upgrade -y'

source <(kubectl completion zsh) && kubectl completion zsh > "${fpath[1]}/_kubectl"